<Project>

  <Target Name="CopyCefNativeToOutput" AfterTargets="Build">
    <ItemGroup>
      <_CefNativeAssets Include="$(MSBuildThisFileDirectory)..\runtimes\$(RuntimeIdentifier)\native\*"
                        Condition="'$(RuntimeIdentifier)' != ''" />
    </ItemGroup>

    <Copy SourceFiles="@(_CefNativeAssets)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true"
          Condition="'@(_CefNativeAssets)' != ''" />
  </Target>

  <Target Name="CopyCefNativeToPublish" AfterTargets="Publish">
    <ItemGroup>
      <_CefNativePublishAssets Include="$(MSBuildThisFileDirectory)..\runtimes\$(RuntimeIdentifier)\native\*"
                               Condition="'$(RuntimeIdentifier)' != ''" />
    </ItemGroup>

    <Copy SourceFiles="@(_CefNativePublishAssets)"
          DestinationFolder="$(PublishDir)"
          SkipUnchangedFiles="true"
          Condition="'@(_CefNativePublishAssets)' != ''" />
  </Target>

</Project>