<Project>

  <!-- Windows / Linux -->
  <Target Name="CopyCefNativeToOutput" AfterTargets="Build"
    Condition="'$(RuntimeIdentifier)' != 'osx-x64'">
    <ItemGroup>
      <_CefNativeAssets
        Include="$(MSBuildThisFileDirectory)..\runtimes\$(RuntimeIdentifier)\native\**\*"
        Condition="'$(RuntimeIdentifier)' != ''" />
    </ItemGroup>

    <Copy SourceFiles="@(_CefNativeAssets)"
      DestinationFolder="$(OutputPath)%(RecursiveDir)"
      SkipUnchangedFiles="true"
      Condition="'@(_CefNativeAssets)' != ''" />
  </Target>

  <Target Name="CopyCefNativeToPublish" AfterTargets="Publish"
    Condition="'$(RuntimeIdentifier)' != 'osx-x64'">
    <ItemGroup>
      <_CefNativePublishAssets
        Include="$(MSBuildThisFileDirectory)..\runtimes\$(RuntimeIdentifier)\native\**\*"
        Condition="'$(RuntimeIdentifier)' != ''" />

    </ItemGroup>

    <Copy SourceFiles="@(_CefNativePublishAssets)"
      DestinationFolder="$(PublishDir)%(RecursiveDir)"
      SkipUnchangedFiles="true"
      Condition="'@(_CefNativePublishAssets)' != ''" />
  </Target>

  <!-- Mac -->
  <Target Name="ExtractCefNativeMacOSToOutput" AfterTargets="Build"
    Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
    <Exec
      Command="ditto -x -k '$(MSBuildThisFileDirectory)..\runtimes\osx-x64\native.zip' '$(OutputPath)'" />
  </Target>

  <Target Name="ExtractCefNativeMacOSToPublish" AfterTargets="Publish"
    Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
    <Exec
      Command="ditto -x -k '$(MSBuildThisFileDirectory)..\runtimes\osx-x64\native.zip' '$(PublishDir)'" />
  </Target>
</Project>